### ISSUE TITLE
Android instructions?

### ISSUE THREAD

**Issue by mnjm97** [3rl-io/spidgets-3dof#7]
It's not clear on how to run this on android
the readme says Android doesn't require installation 
but then how to "Run bin/ar-server in a terminal"?
i tried termux but that didn't work.

**Comment by kkota1** [comment]
When you visit this page on your android, do the phone sensors pass through? https://3rl.io/compat/

Currently you need to use remote debugging or some other network setup if you want to edit the code while using. I haven't tried it with termux yet. It may be possible to use the bun steps (manual build) to get the webserver running locally. If I can make a bin for termux I'll let you know

**Comment by kkota1** [comment]
I'm going to move the android setup to its own repo called "spidgets-mobile" soon, which won't have any of the bins or websocket, so that may make it simpler to set up with termux

**Comment by mnjm97** [comment]
I'm sorry for being dumb.  so the webserver currently needs to be run on a desktop for android to use?  I am still not following how to get this to work with android?

**Comment by kkota1** [comment]
No worries, the instructions aren’t very clear yet. Yes currently for
android you need to run it on your desktop and connect over local network
to test. It will be something like 192.168.0.XX:8000 instead of
localhost:8000

I’m making on a standalone version for termux that should work without
desktop/network

**Comment by mnjm97** [comment]
> When you visit this page on your android, do the phone sensors pass through? https://3rl.io/compat/
> 
It was working before but now I can't seem to get it working.

**Comment by kkota1** [comment]
It’s already working on termux apparently. Just use

npm install
node ar-server.js

Because bun isn’t supported on android

**Comment by kkota1** [comment]
Simplified repo and instructions for mobile, including Android: https://github.com/3rl-io/spidgets-mobile
